imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@MyDirectoryAppBundle/Resources/config/services_app.xml" }

framework:
    #esi:             ~
    translator: { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1.0.0
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

ccetc_directory:
    bundle_name: MyDirectoryAppBundle
    bundle_path: \MyDirectory\AppBundle
    title: My Directory
    logo: bundles/mydirectoryapp/images/logo.gif
#    menu_builder: MyDirectoryAppBundle:Builder:mainMenu
#    layout_template: MyDirectoryAppBundle::layout.html.twig
    copyright: My Company 2013
    contact_email: contact@email.com
    admin_email: admin@email.com
    og_description: your description
    og_url: http://yoururl
    google_maps_key: AIzaSyChMbi3EKId5hm4KhE5p4h1Gm_L6TGbECY
    google_analytics_account: UA-NNNNNNNNN-1
    registration_setting: required

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        ccetc.directory.block.admin_listing_approval:
            contexts: [admin]

sonata_admin:
    title:      My Directory Admin
    title_logo: bundles/mydirectoryapp/images/logo.gif
    templates:
        layout:  CCETCDirectoryBundle::admin_layout.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: ccetc.directory.block.admin_listing_approval }
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
          listings:
            label: Listings
            items: [ccetc.directory.admin.listing]
          users:
            label: Users
            items: [ccetc.directoryuser.admin.user]
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: MyDirectory\AppBundle\Entity\User            