mydirectory_app:
    resource: "@MyDirectoryAppBundle/Resources/config/routing_app.yml"
    prefix:   /

ccetc_directory:
    resource: "@CCETCDirectoryBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin